---
apiVersion: admin.gloo.solo.io/v2
kind: Workspace
metadata:
  name: app-b
  namespace: gloo-mesh
  labels:
    allow_ingress: "true"
spec:
  workloadClusters:
  - name: 'mgmt'
    namespaces:
    - name: app-b-config
  - name: '*'
    namespaces:
    - name: app-b
    - name: bookinfo
---
apiVersion: admin.gloo.solo.io/v2
kind: WorkspaceSettings
metadata:
  name: app-b
  namespace: app-b-config
spec:
  exportTo:
  - workspaces:
    - name: ops-team
    resources:
    - kind: ALL
  importFrom:
  - workspaces:
    - name: ops-team
    resources:
    - kind: SERVICE
    - kind: VIRTUAL_DESTINATION
    - kind: EXTERNAL_SERVICE
  options:
    federation:
      enabled: false
      serviceSelector:
      - {}
    serviceIsolation:
      enabled: false
      trimProxyConfig: false
